services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    image: frontend
    restart: always
    hostname: frontend
    ports: 
      - 8080:8080
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    image: backend
    hostname: backend
    restart: always